=begin
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
=end
def fibonacci(limit = 4_000_000)
  a, b = 1, 2
  c = a+b
  acum = 2
  while c < limit
    c = a + b
	a = b
	b = c
	if c < limit && c % 2 == 0 
		acum += c
	elsif c >= limit
		b = a
		c = b
		break
	end
  end
  acum
end	
puts fibonacci()