=begin
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
=end
def fibonacci
	a, b = 1, 2
	c = a+b
	acum = 2
	while c < 4_000_000
		c = a + b
		a = b
		b = c
		if c < 4_000_000 && c % 2 == 0 
			acum += c
		elsif c >= 4_000_000
			b = a
			c = b
			break
		end
	end
	acum
end	
puts fibonacci