# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

class FibonacciSeries
  def fibonacci(limit = 0)
    limit = limit.to_i
    a = 0
    b = 1
    c = a + b
    acum = 0
    while c < limit
      c = a + b
      a = b
      b = c
      acum += c if c % 2 == 0
    end
    acum
  end
end